//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainInfo
    {
        public int ID { get; set; }
        public int idAirplane { get; set; }
        public int idRoute { get; set; }
        public int idAdditionalInformation { get; set; }
    
        public virtual AdditionalInformation AdditionalInformation { get; set; }
        public virtual Airplane Airplane { get; set; }
        public virtual Route Route { get; set; }
    }
}
